# Data Integration (In Progress)
**IS 477 Course Project** | Sage Kim & Kyna Tyagi

In [2]:
import pandas as pd
import numpy as np

In [3]:
gdp_raw = pd.read_csv('worldbank_gdp_raw.csv', skiprows=4)
gdp_raw.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,28440.041688,30082.158423,30645.890602,22759.807175,26749.329609,30975.998912,35718.753119,39498.594129,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.089204,186.909053,197.367547,225.400079,208.962717,226.836135,...,1528.104224,1552.073722,1507.085600,1351.591669,1562.416175,1679.327622,1571.449189,1615.396356,NaN,NaN
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.936832,127.451040,133.823783,139.004980,148.545883,155.561897,...,1574.230564,1720.140092,2216.385055,2030.861659,2112.794076,2138.473153,1841.855064,1411.337029,NaN,NaN
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2790.718869,2860.093648,2493.678844,1759.356199,2303.908127,3682.113151,2916.136633,2665.874448,NaN,NaN

In [4]:
fao_raw = pd.read_csv('foastat_cereal_raw.csv')
fao_raw.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,QCL,Crops and livestock products,32,Argentina,5510,Production,1199.9,Cereals n.e.c.,1961,1961,t,16000.0,A,Official figure,NaN
1,QCL,Crops and livestock products,32,Argentina,5510,Production,1199.9,Cereals n.e.c.,1962,1962,t,14000.0,A,Official figure,NaN
2,QCL,Crops and livestock products,32,Argentina,5510,Production,1199.9,Cereals n.e.c.,1963,1963,t,15000.0,A,Official figure,NaN
3,QCL,Crops and livestock products,32,Argentina,5510,Production,1199.9,Cereals n.e.c.,1964,1964,t,17000.0,A,Official figure,NaN
4,QCL,Crops and livestock products,32,Argentina,5510,Production,1199.9,Cereals n.e.c.,1965,1965,t,20000.0,A,Official figure,NaN

In [8]:
print('Countries:', gdp_raw['Country Name'].nunique())
print('Countries:', fao_raw['Area'].nunique())

Countries: 266
Countries: 71

In [9]:
print(gdp_raw['Country Name'].unique())

['Aruba' 'Africa Eastern and Southern' 'Afghanistan'
 'Africa Western and Central' 'Angola' 'Albania' 'Andorra' 'Arab World'
 'United Arab Emirates' 'Argentina' 'Armenia' 'American Samoa'
 'Antigua and Barbuda' 'Australia' 'Austria' 'Azerbaijan' 'Burundi'
 'Belgium' 'Benin' 'Burkina Faso' 'Bangladesh' 'Bulgaria' 'Bahrain'
 'Bahamas, The' 'Bosnia and Herzegovina' 'Belarus' 'Belize' 'Bermuda'
 'Bolivia' 'Brazil' 'Barbados' 'Brunei Darussalam' 'Bhutan' 'Botswana'
 'Central African Republic' 'Canada' 'Central Europe and the Baltics'
 'Switzerland' 'Channel Islands' 'Chile' 'China' "Cote d'Ivoire"
 'Cameroon' 'Congo, Dem. Rep.' 'Congo, Rep.' 'Colombia' 'Comoros'
 'Cabo Verde' 'Costa Rica' 'Caribbean small states' 'Cuba' 'Curacao'
 'Cayman Islands' 'Cyprus' 'Czechia' 'Germany' 'Djibouti' 'Dominica'
 'Denmark' 'Dominican Republic' 'Algeria'
 'East Asia & Pacific (excluding high income)'
 'Early-demographic dividend' 'East Asia & Pacific'
 'Europe & Central Asia (excluding high income)' 'Europe & Central Asia'
 'Ecuador' 'Egypt, Arab Rep.' 'Euro area' 'Eritrea' 'Spain' 'Estonia'
 'Ethiopia' 'European Union' 'Fragile and conflict affected situations'
 'Finland' 'Fiji' 'France' 'Faroe Islands' 'Micronesia, Fed. Sts.' 'Gabon'
 'United Kingdom' 'Georgia' 'Ghana' 'Gibraltar' 'Guinea' 'Gambia, The'
 'Guinea-Bissau' 'Equatorial Guinea' 'Greece' 'Grenada' 'Greenland'
 'Guatemala' 'Guam' 'Guyana' 'High income' 'Hong Kong SAR, China'
 'Honduras' 'Heavily indebted poor countries (HIPC)' 'Croatia' 'Haiti'
 'Hungary' 'IBRD only' 'IDA & IBRD total' 'IDA total' 'IDA blend'
 'Indonesia' 'IDA only' 'Isle of Man' 'India' 'Not classified' 'Ireland'
 'Iran, Islamic Rep.' 'Iraq' 'Iceland' 'Israel' 'Italy' 'Jamaica' 'Jordan'
 'Japan' 'Kazakhstan' 'Kenya' 'Kyrgyz Republic' 'Cambodia' 'Kiribati'
 'St. Kitts and Nevis' 'Korea, Rep.' 'Kuwait'
 'Latin America & Caribbean (excluding high income)' 'Lao PDR' 'Lebanon'
 'Liberia' 'Libya' 'St. Lucia' 'Latin America & Caribbean'
 'Least developed countries: UN classification' 'Low income'
 'Liechtenstein' 'Sri Lanka' 'Lower middle income' 'Low & middle income'
 'Lesotho' 'Late-demographic dividend' 'Lithuania' 'Luxembourg' 'Latvia'
 'Macao SAR, China' 'St. Martin (French part)' 'Morocco' 'Monaco'
 'Moldova' 'Madagascar' 'Maldives'
 'Middle East, North Africa, Afghanistan & Pakistan' 'Mexico'
 'Marshall Islands' 'Middle income' 'North Macedonia' 'Mali' 'Malta'
 'Myanmar'
 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)'
 'Montenegro' 'Mongolia' 'Northern Mariana Islands' 'Mozambique'
 'Mauritania' 'Mauritius' 'Malawi' 'Malaysia' 'North America' 'Namibia'
 'New Caledonia' 'Niger' 'Nigeria' 'Nicaragua' 'Netherlands' 'Norway'
 'Nepal' 'Nauru' 'New Zealand' 'OECD members' 'Oman' 'Other small states'
 'Pakistan' 'Panama' 'Peru' 'Philippines' 'Palau' 'Papua New Guinea'
 'Poland' 'Pre-demographic dividend' 'Puerto Rico (US)'
 "Korea, Dem. People's Rep." 'Portugal' 'Paraguay' 'West Bank and Gaza'
 'Pacific island small states' 'Post-demographic dividend'
 'French Polynesia' 'Qatar' 'Romania' 'Russian Federation' 'Rwanda'
 'South Asia' 'Saudi Arabia' 'Sudan' 'Senegal' 'Singapore'
 'Solomon Islands' 'Sierra Leone' 'El Salvador' 'San Marino'
 'Somalia, Fed. Rep.' 'Serbia'
 'Sub-Saharan Africa (excluding high income)' 'South Sudan'
 'Sub-Saharan Africa' 'Small states' 'Sao Tome and Principe' 'Suriname'
 'Slovak Republic' 'Slovenia' 'Sweden' 'Eswatini'
 'Sint Maarten (Dutch part)' 'Seychelles' 'Syrian Arab Republic'
 'Turks and Caicos Islands' 'Chad'
 'East Asia & Pacific (IDA & IBRD countries)'
 'Europe & Central Asia (IDA & IBRD countries)' 'Togo' 'Thailand'
 'Tajikistan' 'Turkmenistan'
 'Latin America & the Caribbean (IDA & IBRD countries)' 'Timor-Leste'
 'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)' 'Tonga'
 'South Asia (IDA & IBRD)' 'Sub-Saharan Africa (IDA & IBRD countries)'
 'Trinidad and Tobago' 'Tunisia' 'Turkiye' 'Tuvalu' 'Tanzania' 'Uganda'
 'Ukraine' 'Upper middle income' 'Uruguay' 'United States' 'Uzbekistan'
 'St. Vincent and the Grenadines' 'Venezuela, RB' 'British Virgin Islands'
 'Virgin Islands (U.S.)' 'Viet Nam' 'Vanuatu' 'World' 'Samoa' 'Kosovo'
 'Yemen, Rep.' 'South Africa' 'Zambia' 'Zimbabwe']

In [11]:
print(fao_raw['Area'].unique())

['Argentina' 'Armenia' 'Austria' 'Belarus' 'Belgium' 'Bhutan'
 'Bolivia (Plurinational State of)' 'Botswana' 'Bulgaria' 'Burundi' 'Chad'
 'China' 'China, mainland' 'China, Taiwan Province of' 'Colombia' 'Congo'
 'Croatia' 'Czechia' 'Czechoslovakia' 'Eritrea' 'Estonia' 'Ethiopia'
 'Ethiopia PDR' 'Finland' 'France' 'Gambia' 'Georgia' 'Greece'
 'Guinea-Bissau' 'Hungary' 'Ireland' 'Italy' 'Jordan' 'Kazakhstan'
 'Latvia' 'Lithuania' 'Luxembourg' 'Mali' 'Malta' 'Mexico' 'Mongolia'
 'Morocco' 'Myanmar' 'New Zealand' 'Niger' 'Oman' 'Palestine' 'Peru'
 'Poland' 'Portugal' 'Qatar' 'Republic of Korea' 'Romania'
 'Russian Federation' 'Saudi Arabia' 'Senegal' 'Serbia' 'Sierra Leone'
 'Slovakia' 'Slovenia' 'South Africa' 'Spain' 'Switzerland' 'Thailand'
 'Togo' 'Tunisia' 'Ukraine' 'United Republic of Tanzania' 'USSR'
 'Uzbekistan' 'Zimbabwe']

In [13]:
for name in fao_raw['Area'].unique():
    if name not in gdp_raw['Country Name'].values:
        print(name)

Bolivia (Plurinational State of)
China, mainland
China, Taiwan Province of
Congo
Czechoslovakia
Ethiopia PDR
Gambia
Palestine
Republic of Korea
Slovakia
United Republic of Tanzania
USSR

In [21]:
fao_raw[fao_raw['Area'] == 'China']

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
525,QCL,Crops and livestock products,159,China,5510,Production,1199.9,Cereals n.e.c.,1961,1961,t,1000.00,E,Estimated value,NaN
526,QCL,Crops and livestock products,159,China,5510,Production,1199.9,Cereals n.e.c.,1962,1962,t,1000.00,E,Estimated value,NaN
527,QCL,Crops and livestock products,159,China,5510,Production,1199.9,Cereals n.e.c.,1963,1963,t,2000.00,E,Estimated value,NaN
528,QCL,Crops and livestock products,159,China,5510,Production,1199.9,Cereals n.e.c.,1964,1964,t,2000.00,E,Estimated value,NaN
529,QCL,Crops and livestock products,159,China,5510,Production,1199.9,Cereals n.e.c.,1965,1965,t,3000.00,E,Estimated value,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,QCL,Crops and livestock products,159,China,5510,Production,1199.9,Cereals n.e.c.,2020,2020,t,44931.04,E,Estimated value,NaN
585,QCL,Crops and livestock products,159,China,5510,Production,1199.9,Cereals n.e.c.,2021,2021,t,44091.55,E,Estimated value,NaN
586,QCL,Crops and livestock products,159,China,5510,Production,1199.9,Cereals n.e.c.,2022,2022,t,44385.73,E,Estimated value,NaN
587,QCL,Crops and livestock products,159,China,5510,Production,1199.9,Cereals n.e.c.,2023,2023,t,44470.34,E,Estimated value,NaN
588,QCL,Crops and livestock products,159,China,5510,Production,1199.9,Cereals n.e.c.,2024,2024,t,44317.59,E,Estimated value,NaN

In [22]:
fao_raw[fao_raw['Area'] == 'China, mainland'].head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
589,QCL,Crops and livestock products,156,"China, mainland",5510,Production,1199.9,Cereals n.e.c.,1991,1991,t,NaN,M,Missing value; data cannot exist,NaN
590,QCL,Crops and livestock products,156,"China, mainland",5510,Production,1199.9,Cereals n.e.c.,1992,1992,t,NaN,M,Missing value; data cannot exist,NaN
591,QCL,Crops and livestock products,156,"China, mainland",5510,Production,1199.9,Cereals n.e.c.,1993,1993,t,NaN,M,Missing value; data cannot exist,NaN
592,QCL,Crops and livestock products,156,"China, mainland",5510,Production,1199.9,Cereals n.e.c.,1994,1994,t,NaN,M,Missing value; data cannot exist,NaN
593,QCL,Crops and livestock products,156,"China, mainland",5510,Production,1199.9,Cereals n.e.c.,1995,1995,t,NaN,M,Missing value; data cannot exist,NaN

In [18]:
fao_raw[fao_raw['Area'] == 'China, Taiwan Province of']

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
623,QCL,Crops and livestock products,158,"China, Taiwan Province of",5510,Production,1199.9,Cereals n.e.c.,1961,1961,t,1000.00,E,Estimated value,NaN
624,QCL,Crops and livestock products,158,"China, Taiwan Province of",5510,Production,1199.9,Cereals n.e.c.,1962,1962,t,1000.00,E,Estimated value,NaN
625,QCL,Crops and livestock products,158,"China, Taiwan Province of",5510,Production,1199.9,Cereals n.e.c.,1963,1963,t,2000.00,E,Estimated value,NaN
626,QCL,Crops and livestock products,158,"China, Taiwan Province of",5510,Production,1199.9,Cereals n.e.c.,1964,1964,t,2000.00,E,Estimated value,NaN
627,QCL,Crops and livestock products,158,"China, Taiwan Province of",5510,Production,1199.9,Cereals n.e.c.,1965,1965,t,3000.00,E,Estimated value,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
682,QCL,Crops and livestock products,158,"China, Taiwan Province of",5510,Production,1199.9,Cereals n.e.c.,2020,2020,t,402.64,I,Value imputed by a receiving agency,NaN
683,QCL,Crops and livestock products,158,"China, Taiwan Province of",5510,Production,1199.9,Cereals n.e.c.,2021,2021,t,402.07,I,Value imputed by a receiving agency,NaN
684,QCL,Crops and livestock products,158,"China, Taiwan Province of",5510,Production,1199.9,Cereals n.e.c.,2022,2022,t,402.18,I,Value imputed by a receiving agency,NaN
685,QCL,Crops and livestock products,158,"China, Taiwan Province of",5510,Production,1199.9,Cereals n.e.c.,2023,2023,t,403.19,I,Value imputed by a receiving agency,NaN
686,QCL,Crops and livestock products,158,"China, Taiwan Province of",5510,Production,1199.9,Cereals n.e.c.,2024,2024,t,404.20,I,Value imputed by a receiving agency,NaN

In [24]:
gdp_raw[gdp_raw['Country Name'] == 'China']

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
40,China,CHN,GDP per capita (current US$),NY.GDP.PCAP.CD,89.715075,75.965501,71.061685,74.468154,85.661107,98.668169,...,8979.676527,10085.663815,10342.900952,10627.463799,12887.435724,12970.605641,12951.17824,13303.148154,NaN,NaN

In [25]:
country_name_map = {
    'Bolivia (Plurinational State of)': 'Bolivia',
    'China, mainland':                  'China',
    'Congo':                            'Congo, Rep.',
    'Gambia':                           'Gambia, The',
    'Palestine':                        'West Bank and Gaza',
    'Republic of Korea':                'Korea, Rep.',
    'Slovakia':                         'Slovak Republic',
    'United Republic of Tanzania':      'Tanzania',
}

In [ ]:
fao_clean = fao_raw.copy()
fao_clean['Country_Name_WB'] = fao_clean['Area'].replace(country_name_map)
fao_clean[fao_clean]

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note,Country_Name_WB
589,QCL,Crops and livestock products,156,"China, mainland",5510,Production,1199.9,Cereals n.e.c.,1991,1991,t,NaN,M,Missing value; data cannot exist,NaN,China
590,QCL,Crops and livestock products,156,"China, mainland",5510,Production,1199.9,Cereals n.e.c.,1992,1992,t,NaN,M,Missing value; data cannot exist,NaN,China
591,QCL,Crops and livestock products,156,"China, mainland",5510,Production,1199.9,Cereals n.e.c.,1993,1993,t,NaN,M,Missing value; data cannot exist,NaN,China
592,QCL,Crops and livestock products,156,"China, mainland",5510,Production,1199.9,Cereals n.e.c.,1994,1994,t,NaN,M,Missing value; data cannot exist,NaN,China
593,QCL,Crops and livestock products,156,"China, mainland",5510,Production,1199.9,Cereals n.e.c.,1995,1995,t,NaN,M,Missing value; data cannot exist,NaN,China